---
packages:
  - python3-pip
  - "{{ python_version }}-dev"
  - "{{ python_version }}-venv"
  - libpq-dev
  - postgresql
  - postgresql-contrib
  - redis-server
  - git
  - nginx
  - acl #https://github.com/plone/ansible.plone_server/issues/86#issuecomment-226457346
  - net-tools
  - software-properties-common
  - python3-certbot-nginx

python_version: python3.9 #specify python version here

server_name: a54832fd-068a-43be-9779-79d119491c5c.fr.bw-cloud-instance.org  #corresponds to bwCloud Hostname
certbot_mail_address: hiwis.shikano@uni-konstanz.de




