---
extra_packages:
  - python3-pip
  - python3.9.9-dev #specify python version here
  - python3.9.9-venv
  - libpq-dev
  - postgresql
  - postgresql-contrib
  - redis-server
  - git
  - nginx
  - htop

