- hosts: all
  gather_facts: no #facts are built in variables like "ansible_distribution"(the os the host runs)
  become: no #become root (can be dangerous, because root can do anything on server)
  vars_files:
    - group_vars/main.yml #tell ansible where it can find variabales
    - group_vars/secrets.yml #encrypted file containing passwords
  tasks:

    - name: Updating and upgrading packages
      become: yes #safe option is to become root only for a task that requires it
      apt:
        upgrade: yes
        update_cache: yes

    - name: Installing required packages. This can also take a while.
      become: yes
      package:
        name: "{{ packages }}"
        state: present #ensures package is installed (wont reinstall if thats already the case)

    - name: Making sure psycopg2 is installed #needed for the ansible postgre module
      become: yes #somehow it needs a sudo during installation for ansible to work with it
      pip:
        name: psycopg2
        state: present

    - name: Creating postgre database #https://medium.com/splunkuserdeveloperadministrator/creating-postgresql-database-with-ansible-da65878b782f
      become: yes
      become_user: postgres
      community.postgresql.postgresql_db:
        name=django_db
        template='template0' #default template

    - name: Setting db users password
      become: yes
      become_user: postgres
      community.postgresql.postgresql_user:
        db=postgres
        name=django_db
        password={{ db_password }}

    - name: Making postgre trust IP4 and IP6 instead of md5 #https://www.postgresql.org/docs/9.3/auth-pg-hba-conf.html
      become: true
      replace: #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/replace_module.html
        path: /etc/postgresql/12/main/pg_hba.conf
        regexp:  "{{ item.regexp }}"
        replace: "{{ item.replace }}"
        backup: yes
      loop:
        - { regexp: 'host\s*all\s*all\s*127.0.0.1\/32\s*md5(.*)', replace: 'host    all             all             127.0.0.1/32            trust' } #somehow this only works with these quotes ' '
        - { regexp: 'host\s*all\s*all\s*::1\/128\s*md5(.*)', replace: 'host    all             all             ::1/128                 trust' }

    - name: Restarting postgre
      become: yes
      service:
        name: postgresql
        state: restarted

    - name: Setting environment variables #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html
      become: yes
      ansible.builtin.template:
        src: templates/envvars.j2
        dest: /etc/profile.d/envvars.sh

    - name: logout and login to refresh environment #not sure if necessary #not sure if necessary but cant hurt
      meta: reset_connection

    - name: Downloading repo containing otree project #currently uses my account, maybe we can use the hiwi account with an access token in the future
      git: #https://www.middlewareinventory.com/blog/ansible-git-example/
        repo: 'https://{{gituser}}:{{gitpass}}@github.com/hiwis-shikano/OnlineExamERM_2021_22.git'
        dest: "/home/ubuntu/otree"
        force: yes

    - name: Creating virtual env #remember to specify correct python version
      command: "{{ python_version }} -m venv venv_otree"

    - name: Install requirements (based on requirements.txt) inside of virtual environment
      pip:
        requirements: /home/ubuntu/otree/requirements.txt
        virtualenv: /home/ubuntu/venv_otree
        virtualenv_python: python3.9

    - name: Installing circus inside of virtual env
      pip:
        name: circus
        virtualenv: /home/ubuntu/venv_otree
        virtualenv_python: python3.9
        state: present

    - name: Resetting otree database
      shell: |
          . ~/venv_otree/bin/activate
          cd ~/otree
          yes | otree resetdb #pipe yes input into otree command

    - name: Copying circus config file to server
      ansible.builtin.copy:
        src: templates/circus.ini
        dest: ~/otree/circus.ini

    - name: Removing default nginx page
      become: yes
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copying nginx config to server
      become: yes
      ansible.builtin.template:
        src: templates/otree.j2
        dest: /etc/nginx/sites-available/oTree

    - name: Creating a symbolic link
      become: yes
      ansible.builtin.file:
        src: /etc/nginx/sites-available/oTree
        dest: /etc/nginx/sites-enabled/oTree
        state: link

    - name: Restarting nginx
      become: yes
      service:
        name: nginx
        state: restarted

    - name: Creating and installing ssl certificate (for https) using certbot
      become: yes
      shell: 'certbot --nginx -d {{  server_name  }} -d cdm-exam.polver.uni-konstanz.de -m {{  certbot_mail_address  }} --agree-tos --noninteractive --redirect --expand'

    - name: Reboot a slow machine that might have lots of updates to apply
      become: yes
      reboot:
        reboot_timeout: 3600

    - name: bugfix for "Unsupported upgrade request" #https://groups.google.com/g/otree/c/sj4Ac2dIpRc
      shell: |
        . /home/ubuntu/venv_otree/bin/activate
        pip3 install uvicorn[standard]==0.13.4

    - name: Starting circus
      become: yes
      become_flags: "-i" #login-specific resource files such as .profile or .login will be read by the shell
      shell: |
        . /home/ubuntu/venv_otree/bin/activate
        cd /home/ubuntu/otree
        circusd --daemon circus.ini --log-output=/home/ubuntu/otree/circus-logs.txt

















    




















