- hosts: all
  gather_facts: no #facts are built in variables like "ansible_distribution"(the os the host runs)
  become: no #become root (can be dangerous, because root can do anything on server)
  vars_files:
    - group_vars/main.yml #tell ansible where it can find variabales
    - group_vars/secrets.yml #encrypted file containing passwords
  tasks:

  - name: Stopping circus
    shell: |
      . /home/ubuntu/venv_otree/bin/activate
      cd /home/ubuntu/otree
      circusctl quit

  - name: Download repo containing otree project
    git: #https://www.middlewareinventory.com/blog/ansible-git-example/
      repo: 'https://{{gituser}}:{{gitpass}}@github.com/hiwis-shikano/OnlineExamERM_2021_22.git' #currently uses my account, maybe we can use the hiwi account with an access token in the future
      dest: "/home/ubuntu/otree"
      force: yes

  - name: Resetting otree database
    shell: |
      . ~/venv_otree/bin/activate
      cd ~/otree
      yes | otree resetdb #pipe yes input into otree command

  - name: Starting circus
    become: yes
    become_flags: "-i" #login-specific resource files such as .profile or .login will be read by the shell
    shell: |
      . /home/ubuntu/venv_otree/bin/activate
      cd /home/ubuntu/otree
      circusd --daemon circus.ini --log-output=/home/ubuntu/otree/circus-logs.txt

  - name: restarting nginx
    become: yes
    service:
      name: nginx
      state: restarted


