- hosts: all
  # facts are built in variables like "ansible_distribution"(the os the host runs)
  gather_facts: no
  # become root (can be dangerous, because root can do anything on server)
  become: no
  # tell ansible where it can find variabales
  vars_files:
    # encrypted file containing e.g. passwords
    - vars/vault.yml
    - vars/settings.yml

  tasks:
  - name: Creating and installing ssl certificate (for https) using certbot
    become: yes
    shell: 'certbot --nginx -d {{  domain  }} -d {{ bw_cloud_hostname }} -m {{  certbot_mail_address  }} --agree-tos --noninteractive --redirect --expand'

  - name: Restarting nginx
    become: yes
    service:
        name: nginx
        state: restarted
